name: PlayerVaults
main: PlayerVaults\PlayerVaults
author: Zeao
api: [2.0.0, 3.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.1]
version: 2.0
description: A PrivateVault plugin, testing on GenisysPro.
commands:
  playervault:
    default: true
    aliases: ["pv"]
permissions:
  playervaults.vault.1:
    default: true
